// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vohbicnzojcuarotzmiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaGJpY256b2pjdWFyb3R6bWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTAyNzcsImV4cCI6MjA3MzM2NjI3N30.j3LTmzATNf1r4JDBVew9Ghu95PDsC9-ofd-isZ4EPmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});